# Introduction to tensorflow




> TensorFlow is a powerful open-source library for building and training machine learning models.


> Real-world applications:

*   Image Recognition
*   Natural Language Processing
*   Time Series Forecasting








*What will we cover in this notebook ?*

* Introduction to tensors (creating tensors)
* Getting information from tensors (tensor attributes)
* Manipulating tensors (tensor operations)
* Tensors and NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow

## 1.  First things first : what version are we using ?

In [2]:
import tensorflow as tf
print(tf.__version__)

2.17.1


Note: we use 2* _ for the version


## 2.  What is a tensor ?

 * If you've ever used NumPy, tensors are kind of like NumPy arrays.
 * The main difference between tensors and NumPy arrays (also an n-dimensional array of numbers) is that tensors can be used on GPUs (graphical processing units) and TPUs (tensor processing units).
 * The benefit of being able to run on GPUs and TPUs is faster computation, this means, if we wanted to find patterns in the numerical representations of our data, we can generally find them faster using GPUs and TPUs.

## 3. Creating a tensor with tf.constant()

This isn't used in practice much, since it is handled with modules, but it helps to get familiar with tensors themselves

In [3]:
scalar= tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0


A scalar is known as a rank 0 tensor. Because it has no dimensions (it's just a number).

### Creating a vector with tf.constant()

In [5]:
vector= tf.constant([7,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

We have one element in the shape section, so this is probably a one dim thingy

In [6]:
vector.ndim

1

### Creating a matrix with tf.constant()

In [7]:
matrix=tf.constant([[7,10],
                    [10,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [10,  7]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
matrix_=tf.constant([[[7,10],
                    [10,7]],
                    [[3,9],
                    [9,3]]])
matrix_

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 7, 10],
        [10,  7]],

       [[ 3,  9],
        [ 9,  3]]], dtype=int32)>

In [10]:
matrix.ndim

2

In [11]:
matrix_=tf.constant([[[7,10],
                    [10,7]],
                   [[3,9],
                    [9,3]],
                   [[2,4],
                    [2,4]]])
matrix_

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 7, 10],
        [10,  7]],

       [[ 3,  9],
        [ 9,  3]],

       [[ 2,  4],
        [ 2,  4]]], dtype=int32)>

In [12]:
matrix_.ndim

3

By default, TensorFlow creates tensors with either an int32 or float32 datatype.

This is known as 32-bit precision (the higher the number, the more precise the number, the more space it takes up on your computer).

### 4. Creating a tensor with tf.variable()

In [13]:
import tensorflow as tf

In [14]:
changeable_variable=tf.Variable([7,10])
changeable_variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [15]:
# Will error (requires the .assign() method)
changeable_tensor[0] = 7
changeable_tensor

NameError: name 'changeable_tensor' is not defined

In [16]:
changeable_variable[1].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [17]:
unchangeable_variable=tf.constant([7,10])
unchangeable_variable

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [18]:
type(unchangeable_variable)

tensorflow.python.framework.ops.EagerTensor

Rarely in practice, you will have to decide whether an attribute needs to be constant or variable, **TensorFlow ** will do it for you.
If one cannot decide, you make it constant then change it to variable.

## 5. Creating random tensors

Why ? Neural networks initialize their weights as random n-dimensional arrays, which are then refined through learning to capture meaningful patterns in the data.

TF.RANDOM

In [19]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal([2,2])
random_1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

In [20]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal([2,2])
random_2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

## 6. Other ways to make tensors

### Make a tensor of all ones


In [22]:
tf.ones(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

### Make a tensor of all zeros

In [23]:
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

### Turn a numpy array and python list into array

In [24]:
# Creating tensors
tensor_a = tf.constant([[1, 2], [3, 4]])
tensor_b = tf.constant([[5, 6], [7, 8]])

# Adding tensors
tensor_sum = tf.add(tensor_a, tensor_b)
print("Tensor Addition:\n", tensor_sum)

# Multiplying tensors (element-wise)
tensor_mul = tf.multiply(tensor_a, tensor_b)
print("Tensor Element-wise Multiplication:\n", tensor_mul)

# Matrix multiplication
tensor_matmul = tf.matmul(tensor_a, tensor_b)
print("Tensor Matrix Multiplication:\n", tensor_matmul)


Tensor Addition:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Tensor Element-wise Multiplication:
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
Tensor Matrix Multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


## 7. Getting information from tensors

In [25]:
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [26]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

### Get various attributes of tensor

In [27]:
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


### Get the first 2 items of each dimension

In [28]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

### Changing the datatype of a tensor

At times, you may need to modify the default datatype of a tensor.

This is often done to reduce precision, such as switching from 32-bit to 16-bit floating-point numbers.

Lower precision is advantageous on devices with limited computational power, like mobile devices, as it reduces the memory and processing requirements.

You can use tf.cast() to adjust a tensor's datatype.

In [29]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])

# Create a new tensor with default datatype (int32)
C = tf.constant([1, 7])
B, C


(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [30]:

# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B


# Change from int32 to float32
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

## 8. Basic Tensor Operations

### Creating Tensors

In [39]:
tensor_a = tf.constant([[1, 2], [3, 4]])
tensor_b = tf.constant([[5, 6], [7, 8]])

### Adding tensors



In [40]:
tensor_sum = tf.add(tensor_a, tensor_b)
print("Tensor Addition:\n", tensor_sum)

Tensor Addition:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


### Multiplying tensors (element-wise)

In [41]:
tensor_mul = tf.multiply(tensor_a, tensor_b)
print("Tensor Element-wise Multiplication:\n", tensor_mul)


Tensor Element-wise Multiplication:
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


### Matrix multiplication

In [42]:
tensor_matmul = tf.matmul(tensor_a, tensor_b)
print("Tensor Matrix Multiplication:\n", tensor_matmul)

Tensor Matrix Multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


## 9. Changing Tensor Shape

### Create a tensor

In [43]:
tensor = tf.constant([1, 2, 3, 4, 5, 6])

### Resahpe the tensor

In [44]:
reshaped_tensor = tf.reshape(tensor, [2, 3])
print("Reshaped Tensor:\n", reshaped_tensor)

Reshaped Tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


### Flatten the tensor

In [45]:
flattened_tensor = tf.reshape(reshaped_tensor, [-1])
print("Flattened Tensor:", flattened_tensor)


Flattened Tensor: tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


## 10. Slicing and Indexing Tensors

In [46]:
# Create a tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slice the tensor
slice = tensor[0:2, 1:]
print("Sliced Tensor:\n", slice)

# Access specific element
element = tensor[2, 1]
print("Element at (2,1):", element)


Sliced Tensor:
 tf.Tensor(
[[2 3]
 [5 6]], shape=(2, 2), dtype=int32)
Element at (2,1): tf.Tensor(8, shape=(), dtype=int32)


## 11. Testing Tensor Precision

In [47]:
# Create tensors in different precisions
tensor_32 = tf.constant([1.1, 2.2, 3.3], dtype=tf.float32)
tensor_16 = tf.constant([1.1, 2.2, 3.3], dtype=tf.float16)

# Compute their sum
sum_32 = tf.reduce_sum(tensor_32)
sum_16 = tf.reduce_sum(tensor_16)

print("Sum with 32-bit precision:", sum_32.numpy())
print("Sum with 16-bit precision:", sum_16.numpy())


Sum with 32-bit precision: 6.6000004
Sum with 16-bit precision: 6.6


## 12.  Using @tf.function to Speed Up Regular Python Functions

@tf.function is a powerful TensorFlow decorator that converts a regular Python function into a TensorFlow graph, optimizing performance and enabling execution on devices like GPUs or TPUs. Here's how to use it:

In [48]:
# Define a simple function
def add_tensors(a, b):
    return a + b

# Convert the function to a TensorFlow graph
@tf.function
def add_tensors_tf(a, b):
    return a + b

# Test with tensors
tensor_a = tf.constant([1, 2, 3], dtype=tf.float32)
tensor_b = tf.constant([4, 5, 6], dtype=tf.float32)

# Measure execution time without @tf.function
import time
start_time = time.time()
print("Without tf.function:", add_tensors(tensor_a, tensor_b))
print("Time without tf.function:", time.time() - start_time)

# Measure execution time with @tf.function
start_time = time.time()
print("With tf.function:", add_tensors_tf(tensor_a, tensor_b))
print("Time with tf.function:", time.time() - start_time)


Without tf.function: tf.Tensor([5. 7. 9.], shape=(3,), dtype=float32)
Time without tf.function: 0.0030770301818847656
With tf.function: tf.Tensor([5. 7. 9.], shape=(3,), dtype=float32)
Time with tf.function: 0.06192660331726074


The results don't represent how fast it works because we're using a very simple operation.

## 13. Using GPUs with TensorFlow

In [49]:
# List available physical devices (CPU and GPU)
physical_devices = tf.config.list_physical_devices()
print("Available physical devices:", physical_devices)

# List GPU devices
gpus = tf.config.list_physical_devices('GPU')
if len(gpus) > 0:
    print(f"GPU is available: {gpus[0]}")
else:
    print("No GPU detected.")


Available physical devices: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
GPU is available: PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')


### Specify which GPU to use for a computation.

In [50]:
# Set TensorFlow to use the first GPU (if available)
if gpus:
    tf.config.set_visible_devices(gpus[0], 'GPU')
    print("Using GPU:", gpus[0])
else:
    print("Using CPU.")

# Create a tensor and run it on GPU
tensor_on_gpu = tf.constant([1.0, 2.0, 3.0])
print("Tensor on GPU:", tensor_on_gpu)


Using GPU: PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')
Tensor on GPU: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


### Using tf.device to Specify Device (GPU or CPU)

In [51]:
with tf.device('/GPU:0'):  # Change to '/CPU:0' to use CPU
    tensor_a = tf.random.normal([10000, 10000])
    tensor_b = tf.random.normal([10000, 10000])
    result = tf.matmul(tensor_a, tensor_b)

print("Computation result on device:", result)


Computation result on device: tf.Tensor(
[[ 172.5944    -153.8392      95.6782    ...  -16.166897   102.85215
   -44.347454 ]
 [ 160.5885     -45.118397   -30.596466  ...  112.45843   -180.09584
   -83.15066  ]
 [-137.80981    -76.96231    -78.77242   ...  -94.38506    269.0589
    19.37499  ]
 ...
 [ -41.204018    22.361132    95.50313   ...  -49.661583   -17.635387
    50.68065  ]
 [ -13.441215   230.37833    108.069756  ... -192.21632    148.42174
  -179.2088   ]
 [-109.298256    72.70763     91.58525   ...  -72.98904   -152.30733
    -6.0772023]], shape=(10000, 10000), dtype=float32)
